- .eslintignore
- .eslintrc.json
- .prettierrc
- components/Button/Button.tsx
- custom-next-env.d.ts
- tsconfig.json
- types/images.d.ts
Apply recent learning about these configs discovered in voter-dapp-v2.
> Reconfigure ts eslint prettier nextenv

- components/Builder/BuilderTabContent.tsx
- components/Footer/Footer.tsx
- components/GlobalStyle/GlobalStyle.ts
- components/Header/Header.tsx
- components/Hero/Hero.tsx
- components/Layout/Layout.tsx
- components/Projects/Projects.tsx
- components/SupportSection/SupportSection.tsx
- components/Tabs/Tabs.tsx
- components/VoteParticipation/VoteParticipation.tsx
- components/VoteTicker/VoteTicker.tsx
- components/Widgets/Widgets.tsx
- components/pages/Home/Home.tsx
- constants/colors.ts
1. Cleaned up Colour variables.
2. Added missing prop to VoteTicker.
Reference Figma for vars.
> improve: remove unnecessary colors and add only colours from current Figma.

- components/Builder/BuilderTabContent.tsx
- components/Footer/Footer.tsx
- components/Header/Header.tsx
- components/SupportSection/SupportSection.tsx
- components/VoteParticipation/VoteParticipation.tsx
- components/VoteTicker/VoteTicker.tsx
hover states for links, buttons, and input.
> feat: button + link + input hover states

- components/Builder/Builder.tsx
- components/VoteParticipation/VoteParticipation.tsx
- components/pages/Home/Home.tsx
- stories/VoteParticipation.stories.tsx
1. Container appears when intersecting
2. Fixed issue with image in the Builder section on small screens.
> feat: Link to app scrolls into view on mobile when intersection the section

- components/Builder/BuilderTabContent.tsx
- components/Footer/Footer.tsx
- components/Header/DesktopHeader.tsx
- components/Header/Header.tsx
- components/Hero/Hero.tsx
- components/HowItWorks/HowItWorks.tsx
- components/Projects/Projects.tsx
- components/SupportSection/SupportSection.tsx
- components/Tabs/Tabs.tsx
- components/VoteParticipation/VoteParticipation.tsx
- components/Widgets/Widgets.tsx
- components/pages/Home/Home.tsx
- hooks/helpers/useIntersectionObserver.ts
1. Hero animations
2. Button / hover effects / navbar (etc) transitions.
3. Project button transitions.
4. Tab content
> feat: animations

- components/Builder/Builder.tsx
- components/Header/DesktopHeader.tsx
- components/Header/Header.tsx
- components/Header/MobileHeader.tsx
- components/HowItWorks/HowItWorks.tsx
- components/Projects/Projects.tsx
- components/Tabs/Tabs.tsx
- components/VoteParticipation/VoteParticipation.tsx
- components/VoteTicker/VoteTicker.tsx
- constants/breakpoints.ts
- package.json
- utils/format.ts
- yarn.lock
1. Header now has solid background in white section
2. Various fixes to responsiveness.
3. Adjust some animations on mobile.
> feature: Header mobile touchups

- components/HowItWorks/HowItWorks.tsx
> feat: red scan animation

- components/Header/Header.tsx
- components/HowItWorks/HowItWorks.tsx
- components/SupportSection/SupportSection.tsx
1. Added video to support section.
2. Touchups to header, other comps.
> feat: Added video to support section. Minor CSS touchups.

- .gitignore
Signed-off-by: Tulun <jaykiraly@gmail.com>
> add .env to git ignore

- components/HowItWorks/HowItWorks.tsx
Signed-off-by: Tulun <jaykiraly@gmail.com>
> feat: remove red scroll animation

- components/SupportSection.tsx
Update careers link to point to our lever page
> fix: update careers link

- components/Tabs.tsx
> fix: Add right code examples

- components/VoteParticipation.tsx
- constant/env.ts
- hooks/queries/useVotingInfo.ts
we want to update aprs while they are 0, to something reasonable
> feat: allow apr override

- package.json
- yarn.lock
> fix: upgrade contracts node

- package.json
- src/components/Osnap/Video.tsx
- src/components/pages/Osnap.tsx
- src/stories/Osnap/Video.stories.tsx
- yarn.lock
Add video section with youtube embed.
[Component story](https://63369c2ea7ac3a411d9b91d9-gcouvcowyq.chromatic.com/?path=/story/osnap-video--default)
[Page story](https://63369c2ea7ac3a411d9b91d9-gcouvcowyq.chromatic.com/?path=/story/pages-osnappage--default)
> feat: video

- src/components/Home/Osnap.tsx
- src/stories/Home/Osnap.stories.tsx
Add osnap section for the home page (has not been added to the actual page yet)
[Component story](https://63369c2ea7ac3a411d9b91d9-vstkdofnfm.chromatic.com/?path=/story/home-osnap--default)
> feat: home page osnap section

- src/components/Footer.tsx
- src/components/Home/Projects.tsx
add some accessibility enhancements
use an optimized image for the footer background
no visual changes
> improve: seo improvements

- src/components/Home/Hero.tsx
- src/components/Home/Osnap.tsx
- src/components/Osnap/Description.tsx
- src/components/Osnap/Hero.tsx
- src/constant/links.tsx
rather go straight to the osnap page when clicking that link in the header
> improve: osnap link behavior

- src/app/osnap-v1/page.tsx
- src/app/osnap/page.tsx
change the directory name to make the v2 page the actual page
> feat: swap page urls

- src/components/OsnapV2/Video.tsx
> chore: update osnap video copy

- src/components/Home/Projects.tsx
> fix: sizing for icons in project grid

- src/app/oval/page.tsx
- src/components/Accordion.tsx
- src/components/OsnapV2/Faq.tsx
- src/components/Oval/BuildSafely.tsx
- src/components/Oval/Faq.tsx
- src/components/Oval/Hero.tsx
- src/components/Oval/OevCreation.tsx
- src/components/Oval/ReclaimOev.tsx
- src/components/Oval/index.ts
- src/components/PlusMinus.tsx
> feat: add faq section

- src/app/oval/page.tsx
- src/components/Oval/BuildSafely.tsx
- src/components/Oval/Ellipsis.tsx
- src/components/Oval/Faq.tsx
- src/components/Oval/Hero.tsx
there was a bug with the ellipses where they were being rendered **on top** of sibling elements, sometimes covering buttons and text. Here I make sure all siblings are rendered on top of the ellipses and also disable pointer events, just in case.
Also removed the OevCreation component.
> Fix remove section fix ellipse bug

- src/components/Header/DesktopHeader.tsx
- src/components/Header/MobileHeader.tsx
- src/components/Header/useHeaderProps.tsx
Oval has no app associated with it, so we remove this link.
> chore: remove launch app link

- package.json
- pnpm-lock.yaml
- src/components/Oval/Animation.tsx
- src/components/Oval/BuildSafely.tsx
- src/components/Oval/Hero.tsx
- src/components/Oval/ReclaimOev.tsx
> chore: replace animations with static images

- src/app/oval/page.tsx
- src/components/Layout.tsx
- src/components/OvalBanner.tsx
we need an oval banner
this shows on all pages except for oval page
> feat: add conditional oval banner

- src/components/Oval/BuildSafely.tsx
- src/components/Oval/CaptureOev.tsx
- src/components/Oval/Faq.tsx
- src/components/Oval/Hero.tsx
- src/components/Oval/OevLost.tsx
- src/components/Oval/ReclaimOev.tsx
had some last minute copy changes
all copy changes from figma
> improve: update latest copy from figma

- src/components/Oval/Faq.tsx
- src/components/Oval/Hero.tsx
- src/components/Oval/OevLost.tsx
> feedback changes

- src/components/OvalBanner.tsx
> make entire banner a link

- package.json
- pnpm-lock.yaml
- src/app/layout.tsx
- src/constant/env.ts
We are using GA for analytics now, this PR installs the script via the latest recommended method.
Setting the Trackng ID as an env variable so we can enable/disable tracking for certain environments.
> Add GA script

- src/components/Layout.tsx
- src/components/Oval/OevLost.tsx
- src/styles/globals.css
Reverts UMAprotocol/uma.xyz#158
> Revert "fix:video background matching"

- next.config.js
people are hitting a  few routes we currently dont handle. we should redirect to appropriate pages
> fix: redirect various routes to external pages

- src/components/Home/OracleTvsChip.tsx
> style oracle tvs chip to new design

- src/constant/links.tsx
Added links to header & footer of all pages
> add links to blog
