components/Footer/Footer.tsx, components/GlobalStyle/GlobalStyle.ts, components/Header/Header.tsx, components/VoteTicker/VoteTicker.tsx, components/VoteTicker/calculateTimeRemaining.ts, components/VoteTicker/index.ts, components/VoteTicker/utils.ts, components/index.ts, constants/colors.ts, hooks/helpers/useInterval.ts, hooks/helpers/useIsomorphicLayoutEffect.ts, package.json, public/assets/clock.svg, stories/VoteTicker.stories.tsx, yarn.lock
1. Vote Ticker widget
2. Some Footer styles / fixes.
=> feat: Vote Ticker for Header and Footer (desktop, stub data)

components/Builder/Builder.tsx, components/Tabs/Tabs.tsx
1. Builder Tabs are fixed to bottom on tablet or less. 
2. Hides / appears based on intersecting section.
Signed-off-by: Tulun <jaykiraly@gmail.com>
=> feat: fixed to tabs to bottom

components/Tabs/Tabs.tsx
Signed-off-by: david <david@umaproject.org>
Tab panels looked clickable because cusror changed to pointer. this removes that so it remains an arrow since its not clickable.
=> fix: remove pointer from cursor on tab panel

components/Tabs/Tabs.tsx
Signed-off-by: david <david@umaproject.org>
Previously the svg on the tabs were off color and it wasnt clear they were changing color on hover. now it changes with the text. 
Unable to get a screenshot of the hover effect, test it with preview url
=> fix: svg hover effect on tabs

components/Hero/Hero.tsx, components/HowItWorks/HowItWorks.tsx, components/VoteParticipation/VoteParticipation.tsx, package.json, yarn.lock
I noticed that we had very high memory use on the page (>800mb) and it was always climbing — classic memory leak. I used the profiler to discover the culprit, which was the lottie animations. It turns out that when lottie animations use something called "repeaters" they will create new instances of the json data over and over again, leading to a leak. See [this issue](https://github.com/airbnb/lottie-web/issues/2070) for details.
I fixed the issue by switching to [this library](https://www.npmjs.com/package/react-lottie-player) which specifically deals with this problem. It also has a better api too, so even better to make the switch.
=> fix: lottie memory leak

components/Builder/Builder.tsx, components/HowItWorks/HowItWorks.tsx, components/SectionHeader/SectionHeader.tsx, components/VoteParticipation/VoteParticipation.tsx, components/VoteTicker/VoteTicker.tsx
Adds entry animations for the section headers that are triggered when they enter the viewport.
Adds the mouse-mapped circle hue-rotate effect from the designs.
=> feat: heading reveal and circle animation

components/Builder/Builder.tsx, components/Footer/Footer.tsx, components/Header/DesktopHeader.tsx, components/Hero/Hero.tsx, components/HowItWorks/HowItWorks.tsx, components/Projects/Projects.tsx, components/SupportSection/SupportSection.tsx, components/VoteParticipation/VoteParticipation.tsx, hooks/helpers/useAddHashToUrl.ts
Now when you scroll into a particular section, it adds the sections id to the url. This lets us determine that the link is active in the header, and highlight the appropriate link accordingly.
=> feat: make links active when scrolling sections

components/Builder.tsx, components/Hero.tsx, components/Projects.tsx, components/SectionHeader.tsx, constant/style/fonts.ts, contexts/ScrollContext.tsx, hooks/helpers/useLoadSectionRefAndId.ts, package.json
I want the header sizes to scale fluidly with the viewport, so that they look proportional on all screen sizes.
* Use `clamp` for small and medium headers to make them fluid
*  Tie the size of the OO icon to the size of the font
=> improve: last tweaks

components/HowItWorks.tsx
Signed-off-by: ryanwolhuter <dev@ryanwolhuter.com>
The animation is upside down on tablet because of how the layout is structured. We must not add a negative margin in that case, because then it will never reach the margin.
=> fix: scroll animation on tablet

components/SupportSection.tsx, components/pages/Home.tsx
Make the whole site available on initial load. This makes our lighthouse slightly worse, but it's not worth the compromise.
* Remove lazy loading of site sections
* Lazy load video since its part of the initial load now
=> fix: navbar does not work on initial load

pages/api/_common.ts, pages/api/get-voting-info.ts
We had some workaround logic in the `get-voting-info` serverless function that was needed for getting the voting contract address on goerli during development. This logic caused us to end up with the wrong contract address in the code.
* Remove goerli workaround logic in contract constructor
=> fix: no active votes in vote ticker

components/Tabs.tsx
we want to be able to customize the doc link based on what code the user clicks on
this adds configurable link and link text for each code example. you can set whatever you want based on this, currently just reproduces previous behavior.
=> feat: allow way to configure doc link under code

components/VoteTicker.tsx
vote countdown differs from voter dapp
we need to use utc time to figure out midnight, rather than local time
=> fix: vote countdown, change to utc

components/VoteTicker.tsx
some people were seeing negative time before the vote
could not find the real cause of this, but most likely due to using local time to seed the utc midnight time, this might sometimes put the day before or after the current utc day, but just a guess
=> fix: use utc time when fetching date, time

src/components/AnimatedLink.tsx, src/components/Footer.tsx, src/components/Header/Header.tsx, src/components/Header/MobileMenu.tsx, src/components/Home/Hero.tsx, src/components/Home/Osnap.tsx, src/components/Home/Projects.tsx, src/components/Home/SupportSection.tsx, src/components/Home/VoteParticipation.tsx, src/components/Osnap/Hero.tsx, src/components/VoteTicker.tsx, src/constant/style/colors.ts, src/styles/globals.css, tailwind.config.ts
fix a couple of issues on mobile:
1. fix the video background not matching in the home page hero on iphones (very hacky but hey it finally works)
2. fix a bug where clicking the "learn more about osnap" link would take you to the footer if the osnap screen
3. use svh instead of dvh to prevent resizing of the section on scroll
4. fix some alignment and padding issues on small screens
5. fix wrong number of grid rows in footer links on small screens
=> improve: mobile tweaks

src/components/Osnap/Faq.tsx
The layout of the FAQs section on the osnap page was a bit wonky at tablet screen sizes. 
Simplify how the layout works so that it shifts to columns earlier and avoids an awkward one column layout that is too narrow for a tablet sized screen.
=> improve: faqs layout

README.md, src/components/GradientBorder.tsx, src/components/OsnapV2/Hero.tsx, src/components/OsnapV2/TvsChip.tsx, src/constant/env.ts
- Created a wrapper component for the gradient border shown in the TVS Chip in Figma for us to use anywhere. The hover effect is optional and might actually be better suited for interactive components.
- Pulling value from env as NEXT_PUBLIC_TVS.
=> feat: add osnap tvs component

.gitignore, src/constant/links.tsx
we are in the process of deprecating projects.uma.xyz in favor of a separate stats page and separate lsp/emp managment method. 
add a link to our dune dash for tvs. also updated git ignore to ignore more env files
=> feat: add stats link to dune dash

src/constant/links.tsx
Weirdly, the link `https:/stats.uma.xyz/` (missing "/" after "https:/") resolves to the full URL but only when running the app locally. In production, this returns a 404.
=> fix: broken dune link

src/app/oval/page.tsx, src/components/Header/DesktopHeader.tsx, src/components/Header/MobileHeader.tsx, src/components/Oval/BuildSafer.tsx, src/components/Oval/CaptureOev.tsx, src/components/Oval/EarnOev.tsx, src/components/Oval/Hero.tsx, src/components/Oval/OevCreation.tsx, src/components/Oval/OevLost.tsx, src/constant/links.tsx
- change "OVAL" to "Oval"
- change "try oval today" to "learn more", link to docs
- Add "oval" decorative text in header (desktop & mobile)
- Add decorative divider component below oevLost section
=> feat: update copy,  links & some styles

README.md, src/components/Footer.tsx, src/components/MailChimpForm.tsx, src/components/Oval/FooterOval.tsx
we want to separate out oval signups from uma signups
add a new env var specificall for mailchimp oval audience. this has already been added to vercel
=> feat: add new mailchimp endpoint for oval

src/components/Home/Hero.tsx, src/components/Home/HowItWorks.tsx, src/components/Home/SupportSection.tsx, src/components/OsnapV2/Hero.tsx, src/components/OsnapV2/TvsChip.tsx, src/components/OsnapV2/Video.tsx, src/components/Oval/BuildSafely.tsx, src/components/Oval/Hero.tsx, src/components/Oval/ReclaimOev.tsx
Some browsers (Chrome) now show controls to play a video in some sort of remote device, wired or wireless. In general we want users to control playback of videos, but NOT if they are purely decorative.
See below, a chromecast button appears over all video elements. I noticed this after updating Chrome so it must be a new feature.
=> fix: remove remoteplayback controls for videos

src/lib/constants.ts
prod is not showing dynamic osnap number
removes extra prod check to enable dune, this might be preventing it from running. just a guess though
=> fix: attempting to fix osnap dune values

package.json, pnpm-lock.yaml, src/app/osnap/page.tsx, src/app/oval/page.tsx, src/components/OsnapV2/Hero.tsx, src/components/OsnapV2/TvsChip.tsx, src/components/Oval/OevLost.tsx, src/lib/constants.ts, src/lib/dune.ts
The `unstable_cache` function does not seem to revalidate..
This PR implements react's new  `cache()` function as recommended here in nextjs docs https://nextjs.org/docs/app/building-your-application/data-fetching/fetching-caching-and-revalidating#fetching-data-on-the-server-with-third-party-libraries
We are also using Vercel's `KV` storage mechanism, which is essentially a wrapper around Upstash's Redis service. We use this is case our function to revalidate the cache throws an error.
=> Fix dune updates

src/components/Layout.tsx, src/components/Oval/OevLost.tsx, src/styles/globals.css
After another chrome upgrade it seems the way the background colors are rendered on mac/chrome has changed again. Since we can not change the color range used by these videos and re-export them, we have to hack together a solution that checks the user agent and sets the background of the page to to match the video's background.
=> fix:video background matching

src/components/Modal.tsx, src/hooks/leadCapture/useLeadCaptureModal.ts
Since we're using a native dialog element for modals we need to listen to "close" events emmited by the actual DOM node so we can run our other param setting and scrolling logic.
=> fix: listen for close events on modal dialog

src/components/MailChimpForm.tsx
text looks grayed out when entering email in this form 
just adds darker text color
=> improve: darken email input color

src/components/Footer.tsx, src/components/OsnapV2/Faq.tsx, src/components/OsnapV2/TryOsnapButton.tsx, src/components/OsnapV2/Video.tsx, src/components/Oval/Faq.tsx, src/components/Oval/OevLost.tsx
Some minor style changes. 
- Ensure inline links are explicitly set to `display: inline`
- Ensure we use the proper `OsnapModalTrigger` and not just a link.
- Less janky transitions when hovering on links
example of link that is not `inline`
fixed
=> inline links, use osnap modal trigger, better transitions

src/app/layout.tsx, src/app/oval/page.tsx, src/components/Home/OracleTvsChip.tsx, src/components/OsnapV2/OsnapTvsChip.tsx, src/components/Oval/OevLost.tsx, src/lib/constants.ts, src/lib/dune.ts, src/utils/misc.ts
Caching seems to be broken on our corporate site. The TVS values are not updating every day, as they should.
Work done:
- Ensure we revalidate all routes, once a day. 
- Format billions for the home page, use the correct tvs figure from Dune (oSnap + Oracle TVS)
=> fix: next cache is serving stale values for TVS on all routes

src/constant/links.tsx
we want to rename instances of oracle to optimistic oracle
only changes the footer from oracle to optimistic oracle
=> fix: rename oracle to optimistic oracle in footer
